# -*- coding: utf-8 -*-
"""자연어처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pYZ2r9Qfi5xNh7z5DMcP-8cWgb2riama
"""

#https://wikidocs.net/158317

!pip install olefile
!wget https://github.com/byungjooyoo/Dataset/raw/main/%EB%85%BC%EB%AC%B8%EC%9A%94%EC%95%BD.hwp

import olefile
f = olefile.OleFileIO('논문요약.hwp')
encoded_text = f.openstream('PrvText').read()
decoded_text = encoded_text.decode('utf-16')
decoded_text

with open("result.txt", 'w') as f:
    f.write(decoded_text)

!pip install pyhwp
!hwp5txt --version
!hwp5txt --output "result1.txt" "논문요약.hwp"

with open("result1.txt", 'r') as f:
    data = f.read()
print(data)

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/byungjooyoo/Dataset/main/hotel_review.csv")
print(df.shape)
print(df.info())
df.head()

print(df.isnull().sum())
print(df['rating'].value_counts())
df['rating'].hist()

def rating_to_label(rating):
    if rating > 3:
        return 1
    else:
        return 0

df['y'] = df['rating'].apply(lambda x: rating_to_label(x))
df["y"].value_counts()

#불용어 처리
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])

!wget https://raw.githubusercontent.com/byungjooyoo/Dataset/main/ko_stopwords.txt
with open("ko_stopwords.txt", 'r') as f:
    stopwords = []
    for line in f.readlines():
        stopwords.append(line.strip())
print('한글 불용어 개수:', len(stopwords))
stopwords[:10]

text = '휴 감정분석 을 준비하고 있습니다.'
para = text.split()
[x for x in para if x not in stopwords]

hotel_stopwords = ['제주', '제주도', '호텔', '리뷰', '숙소', '여행', '트립']
for word in hotel_stopwords:
    stopwords.append(word)
stopwords[-10:]

!pip install konlpy

import konlpy
tagger = konlpy.tag.Okt()

tokens=[]
corpus =[]

#명사 불러오기
for i, sentence in enumerate(df['text']):
    para = tagger.nouns(sentence)
    para = [x for x in para if x not in stopwords]
    para = [x for x in para if len(x) > 1]
    #명사들만 토큰으로 만들어서 리스트에
    tokens.append(para)
    corpus.append(' '.join(para))

print(corpus[:5])
print(tokens[:5])

tokens_p, tokens_n = [],[]
for i, token in enumerate(tokens):
  if df['y'].values[i]== 1:
    tokens_p.append(token)
  else :
    tokens_n.append(token)

print(tokens_p)
print(tokens_n)

from collections import Counter
corpus_n, corpus_p = [], []
for token in tokens_p:
  corpus_p.append(' '.join(token))
for token in tokens_n:
  corpus_n.append(' '.join(token))
corpus_p1 = ' '.join(corpus_p).split()
corpus_n1 = ' '.join(corpus_n).split()
counter_p = Counter(corpus_p1)
counter_n = Counter(corpus_n1)
print(counter_p.most_common(10))
print(counter_n.most_common(10))

#그래프로 시각화
import nltk
import matplotlib.pyplot as plt
pos = nltk.Text(corpus_p1)
neg = nltk.Text(corpus_n1)
plt.rc('font', family='NanumBarunGothic')

plt.figure(1)
pos.plot(30)

plt.figure(2)
neg.plot(30)
plt.show()

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import gensim
g_dictionary = gensim.corpora.Dictionary(tokens)
g_corpus = [g_dictionary.doc2bow(text) for text in tokens]
vector = CountVectorizer(vocabulary=g_dictionary.token2id)
dtm = vector.fit_transform(corpus).toarray()
col = g_dictionary.token2id.keys()
print(dtm.shape)
pd.DataFrame(dtm, columns=col)

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_vectorizer = TfidfTransformer()
tf_idf = tfidf_vectorizer.fit_transform(dtm).toarray()
col = g_dictionary.token2id.keys()
print(tf_idf.shape)
pd.DataFrame(tf_idf, columns=col)

id_to_word = {v: k for k, v in vector.vocabulary_.items()}
print(id_to_word[10])

#12.03
from sklearn.model_selection import train_test_split
X = tf_idf
y=df['y']
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size = 0.3, random_state=256)
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns
import pandas as pd

# 모형 적합과 예측
lr2 = LogisticRegression(random_state = 0)
lr2.fit(x_train, y_train)
y_pred = lr2.predict(x_test)

# 시험용데이터 예측결과 정확도
a = accuracy_score(y_test, y_pred)
p = precision_score(y_test, y_pred)
r =recall_score(y_test, y_pred)
f1= f1_score(y_test, y_pred)
print('Accuracy: %.2f' % a,', Precision: %.2f' % p, ', Recall: %.2f' % r, ', F1: %.2f' % f1 )
tr1 = pd.DataFrame([a, p, r, f1])

# 추정결과 confusion matrix
c_mat = confusion_matrix(y_true = y_test, y_pred = y_pred)
plt.figure(figsize=(4, 3))
sns.heatmap(c_mat, annot=True, annot_kws={'size':15}, cmap='OrRd', fmt='.10g')
plt.title('Confusion Matrix')
plt.show()

#긍정적 의견과 관련된 데이터는 총 726개 인 반면 부정적 의견을 다룬 데이터는 275개로 과소하여 부정적 의견의 데이터를 기준으로 과소추출 방법으로 불균형을 해소하기 위하여 긍정적 의견의 데이터를 랜덤하게 275개만 뽑아서 데이터를 학습용과 시험용으로 분리하는 과정 아래와 같이 코드화하여 실행하였다.
print(y.value_counts())
positive_random_idx = y[y==1].sample(275, random_state=12).index.tolist()
negative_random_idx = y[y==0].sample(275, random_state=12).index.tolist()
random_idx = positive_random_idx + negative_random_idx
# 밸런스 데이터 추출
bal_x = X[random_idx]
bal_y = y[random_idx]
x_train, x_test, y_train, y_test = train_test_split(bal_x, bal_y, test_size=0.25, random_state=1)
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns

# 모형 적합과 예측
lr2 = LogisticRegression(random_state = 0)
lr2.fit(x_train, y_train)
y_pred = lr2.predict(x_test)
# 시험용데이터 예측결과 정확도
a = accuracy_score(y_test, y_pred)
p = precision_score(y_test, y_pred)
r =recall_score(y_test, y_pred)
f1= f1_score(y_test, y_pred)
print('Accuracy: %.2f' % a,', Precision: %.2f' % p, ', Recall: %.2f' % r, ', F1: %.2f' % f1 )
tr2 = pd.DataFrame([a, p, r, f1])

# 추정결과 confusion matrix
c_mat = confusion_matrix(y_true = y_test, y_pred = y_pred)
plt.figure(figsize=(4, 3))
sns.heatmap(c_mat, annot=True, annot_kws={'size':15}, cmap='OrRd', fmt='.10g')
plt.title('Confusion Matrix')
plt.show()

pd.options.display.float_format = '{:.2f}'.format
test_result = pd.concat([tr1.T, tr2.T], axis=0)
test_result.columns=['Accuracy(정확도)', 'Precision(정밀도)', 'Recall(재현율)', 'F1 Score']
test_result.index = ['1차 Imbalance Data', '2차 Under-sampling']
test_result

print(lr2.coef_)
plt.figure(figsize=(10, 8))
plt.bar(range(len(lr2.coef_[0])), lr2.coef_[0])

coef_index = sorted(((value, index) for index, value in enumerate(lr2.coef_[0])), reverse = False)
coef_neg_index = coef_index[:10]
coef_pos_index = coef_index[-10:]
print(coef_pos_index[-3:])
print(coef_neg_index [:3])
print('긍정리뷰 키워드: ', id_to_word[79],id_to_word[92])
print('부정리뷰 키워드: ', id_to_word[199],id_to_word[1020])

#시각
pos_top_word=[]
pos_top_score=[]
for coef in coef_pos_index:
    print(id_to_word[coef[1]], coef[0])
    pos_top_word.append(id_to_word[coef[1]])
    pos_top_score.append(coef[0])

neg_top_word=[]
neg_top_score=[]
for coef in coef_neg_index:
    print(id_to_word[coef[1]], coef[0])
    neg_top_word.append(id_to_word[coef[1]])
    neg_top_score.append(coef[0])

import matplotlib.pyplot as plt

plt.figure(figsize=[10, 8])
plt.barh(neg_top_word, neg_top_score, label = "부정", color = 'r')
plt.barh(pos_top_word, pos_top_score, label = "긍정", color = 'g')
plt.legend()
plt.xlabel('키워드별 Vectorized Score')
plt.ylabel('Top 10 키워드')
plt.title('제주도 호텔 사용 후기 감정어 분석')
plt.show()